micronaut:
  application:
    name: realtimemariadb

datasources:
  default:
    url: jdbc:mariadb://localhost:3306/experiment
    driverClassName: org.mariadb.jdbc.Driver
    host: localhost
    schema: experiment
    username: admin
    password: test
    dialect: MYSQL